### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [TheBoatyMcBoatFace/Sandbox#34]
### Text To Summarize

CivicActions Security Policy
CivicActions has established the following policy to safeguard the security, confidentiality, availability and integrity of CivicActions data, as well as that of our personnel, clients and client website users. All CivicActions employees and contractors are expected to accept and abide by this policy. This policy will be reviewed and updated from time to time. If you have questions or comments about this policy please contact your supervisor. We invite your feedback.
Our primary goals
Protect clients' confidential and personal information;
Reduce potential liability of CivicActions;
Craft a consistent policy that is easy to understand, implement and follow;
Educate/disseminate our best practices for security throughout the CivicActions community;
Demonstrate to clients that we are trustworthy and satisfy contractual requirements for security.
Confidential Information Agreement

**Comment by TheBoatyMcBotFace** [comment]
Hello TheBoatyMcBoatFace, Here is your summary
{"id":"cmpl-6igwGAns0mtTsyQWQJlTjrowIDlCw","object":"text_completion","created":1676109508,"model":"text-davinci-003","choices":[{"text":"\n\nA father and son have an argument about the son's ambition and future plans. The father believes that his son should stay home and help run the family business, while the son wants to explore the world and experience life outside of the family business. The father eventually relents and the son is able to pursue his own dreams.\n\ntl;dr A father and son argue about the son's ambition and future, but the father eventually allows the son to pursue his own dreams.","index":0,"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":14,"completion_tokens":98,"total_tokens":112}}
