### ISSUE TITLE
test

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [TheBoatyMcBoatFace/Sandbox#36]
### Text To Summarize

CivicActions Security Policy
CivicActions has established the following policy to safeguard the security, confidentiality, availability and integrity of CivicActions data, as well as that of our personnel, clients and client website users. All CivicActions employees and contractors are expected to accept and abide by this policy. This policy will be reviewed and updated from time to time. If you have questions or comments about this policy please contact your supervisor. We invite your feedback.

Our primary goals
Protect clients' confidential and personal information;
Reduce potential liability of CivicActions;
Craft a consistent policy that is easy to understand, implement and follow;
Educate/disseminate our best practices for security throughout the CivicActions community;
Demonstrate to clients that we are trustworthy and satisfy contractual requirements for security.
Confidential Information Agreement

**Comment by TheBoatyMcBotFace** [comment]
Hello TheBoatyMcBoatFace, Here is your summary
{"id":"cmpl-6ihLayYFRnK2N9M91YQqJy3t04uDF","object":"text_completion","created":1676111078,"model":"text-davinci-003","choices":[{"text":"\n\nThis text discusses how multiple generations of workers have different needs in the workplace and how employers can adjust their practices to better serve all generations.\n\nEmployers should adjust their practices to better serve the needs of different generations in the workplace, such as baby boomers, millennials, and Gen-Xers.","index":0,"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":12,"completion_tokens":63,"total_tokens":75}}

**Comment by TheBoatyMcBotFace** [comment]
Hello TheBoatyMcBoatFace, Here is your summary
{"id":"cmpl-6ihMDLUUujA9Xq4HfvAHn0SXyPdec","object":"text_completion","created":1676111117,"model":"text-davinci-003","choices":[{"text":"\n\nThis text explains the importance of flexibility in the workplace.\n\ntl;dr: Flexibility in the workplace is key to success and should be a priority for employers.","index":0,"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":12,"completion_tokens":36,"total_tokens":48}}
