### ISSUE TITLE
ci

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [TheBoatyMcBoatFace/Sandbox#37]
### Text To Summarize

"Confidential Information" means information or material which is proprietary to CivicActions and not generally known outside CivicActions, including information or material that you create, learn, or obtain, as well as information we receive in confidence from third parties. For example, this may include without limitation any information disclosed that is subject to applicable non-disclosure protections of CivicActions privacy policies, non-public product plans of CivicActions or 3rd parties, technical and business information, personnel information like salaries, or other sensitive information. Material need not be marked confidential for it to be considered Confidential Information.

**Comment by TheBoatyMcBotFace** [comment]
Hello TheBoatyMcBoatFace, Here is your summary
{"id":"cmpl-6ihP36TbvuTX0eFgMDrtPCRf1sInG","object":"text_completion","created":1676111293,"model":"text-davinci-003","choices":[{"text":"package com.bolsadeideas.springboot.backend.apirest.models.dao;\n\nimport org.springframework.data.jpa.repository.JpaRepository;\n\nimport com.bolsadeideas.springboot.backend.apirest.models.entity.Usuario;\n\npublic interface IUsuarioDao extends JpaRepository<Usuario, Long>{\n\t\n\tpublic Usuario findByUsername(String username);\n\t\n}","index":0,"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":1,"completion_tokens":117,"total_tokens":118}}
