### ISSUE TITLE
dsf<Title of Task>

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [TheBoatyMcBoatFace/Sandbox#39]
### Text To Summarize

"Confidential Information" means information or material which is proprietary to CivicActions and not generally known outside CivicActions, including information or material that you create, learn, or obtain, as well as information we receive in confidence from third parties. For example, this may include without limitation any information disclosed that is subject to applicable non-disclosure protections of CivicActions privacy policies, non-public product plans of CivicActions or 3rd parties, technical and business information, personnel information like salaries, or other sensitive information. Material need not be marked confidential for it to be considered Confidential Information.

**Comment by TheBoatyMcBotFace** [comment]
Hello TheBoatyMcBoatFace, Here is your summary
{"id":"cmpl-6ihRHtMG1GumuMmVUe8wAPMBU5HPk","object":"text_completion","created":1676111431,"model":"text-davinci-003","choices":[{"text":"Q: What is the best way to determine the size of a file in C#?\n\nThe best way to determine the size of a file in C# is to use the FileInfo class. This class provides methods to work with an individual file, including the GetLength() method, which returns the size of the file in bytes. \n\nExample: \n\n// Create a FileInfo object.\nFileInfo file = new FileInfo(@\"C:\\myFile.txt\");\n \n// Get the size of the file.\nlong fileSize = file.Length;","index":0,"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":1,"completion_tokens":122,"total_tokens":123}}
