### ISSUE TITLE
dfs<Title of Task>

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [TheBoatyMcBoatFace/Sandbox#42]
### Text To Summarize

"Confidential Information" means information or material which is proprietary to CivicActions and not generally known outside CivicActions, including information or material that you create, learn, or obtain, as well as information we receive in confidence from third parties. For example, this may include without limitation any information disclosed that is subject to applicable non-disclosure protections of CivicActions privacy policies, non-public product plans of CivicActions or 3rd parties, technical and business information, personnel information like salaries, or other sensitive information. Material need not be marked confidential for it to be considered Confidential Information.

**Comment by TheBoatyMcBotFace** [comment]
Hello TheBoatyMcBoatFace, Here is your summary
{"id":"cmpl-6ihfNnAE8vtZlG5F22HvjguUGiEUx","object":"text_completion","created":1676112305,"model":"text-davinci-003","choices":[{"text":" = <<<HERE\n<h1>View Albums</h1>\n\n<p>\n  <a href=\"album_add_form.php\">Add a new album</a>\n</p>\n\n<table>\n  <tr>\n    <th>Artist</th>\n    <th>Title</th>\n    <th>Genre</th>\n    <th>Year</th>\n    <th>Rating</th>\n    <th>Action</th>\n  </tr>\n\nHERE;\n\n$sql = \"SELECT * FROM album ORDER BY artist\";\n$result = $db->query($sql);\n\nwhile ($row = $result->fetch_assoc()) {\n  $id = $row['id'];\n  $artist = $row['artist'];\n  $title = $row['title'];\n  $genre = $row['genre'];\n  $year = $row['year'];\n  $rating = $row['rating'];\n\n$BODY_CONTENT .= <<<HERE\n  <tr>\n    <td>$artist</","index":0,"logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":6,"completion_tokens":256,"total_tokens":262}}
